# Generated by Django 3.1.2 on 2020-10-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='Address', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='alternate_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='example@emamil.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.IntegerField(default=0),
        ),
    ]
