# Generated by Django 3.1.2 on 2020-10-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_student', '0002_auto_20201012_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
