# Generated by Django 3.1.2 on 2020-10-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_student', '0003_auto_20201012_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254, unique=True),
        ),
    ]
