# Generated by Django 3.1.2 on 2020-10-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_student', '0006_student_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[('M', 'male'), ('F', 'female'), ('N', 'not specified')], default=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(choices=[(0, 'cse'), (1, 'ece')], default='M', max_length=1),
        ),
    ]
