# Generated by Django 3.1.2 on 2020-10-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_student', '0007_auto_20201017_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], default=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.IntegerField(choices=[(0, 'cse'), (1, 'ece')], default=0),
        ),
    ]
